name: Build Info-ZIP
on: workflow_dispatch

jobs:
  build:
    name: Build Info-ZIP for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download and patch sources
      shell: pwsh
      run: .\downloadAndPatch.ps1

    - name: Build for x64
      shell: pwsh
      run: |
        .\build.ps1 x64 zip30 artefacts

    - name: Build for x86
      shell: pwsh
      run: |
        .\build.ps1 x86 zip30 artefacts

    - name: Build for arm64
      shell: pwsh
      run: |
        .\build.ps1 arm64 zip30 artefacts

    - name: Release
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $date = Get-Date
        hub.exe release create (Get-ChildItem artefacts\*.zip | % { '-a', $_.FullName }) `
                -m "Release $(Get-Date -Date $date -Format 'yyyy-MM-dd HH:mm')" `
                -t master (Get-Date -Date $date -Format 'yyyy-MM-dd-HH-mm')
